name: Build and Commit

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Build site
        run: |
          mkdir -p dist
          pandoc index.md \
            -o dist/index.html \
            --css=index.css \
            --embed-resources \
            -s \
            -M title="Purushottam"

      - name: Commit dist folder
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Auto-build site" || echo "No changes"
          git push
